/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* creation time: Thu Dec 03 16:03:11 2015 */
/* tdr version: 2.5.1, build at 20120623 */

#ifndef _TDR_UTIL_H_
#define _TDR_UTIL_H_

#include "TdrPal.h"
#include "TdrBuf.h"

namespace tsf4g_tdr
{


class TdrBufUtil
{
    public:
        static TdrError::ErrorType
            printMultiStr(TdrWriteBuf& buf, const char* str, int times);

        static TdrError::ErrorType
            printVariable(TdrWriteBuf& buf, int indent, char sep,
                        const char* variable, bool withSep = true);

        static TdrError::ErrorType
            printVariable(TdrWriteBuf& buf, int indent, char sep,
                        const char* variable, unsigned int arrIdx, bool withSep = true);

        static TdrError::ErrorType
            printVariable(TdrWriteBuf& buf, int indent, char sep,
                        const char* variable, const char* format, ...);

        static TdrError::ErrorType
            printVariable(TdrWriteBuf& buf, int indent, char sep,
                        const char* variable, unsigned int arrIdx, const char* format, ...);

        static TdrError::ErrorType
            printArray(TdrWriteBuf& buf, int indent, char sep,
                    const char* variable, int64_t count);

        static TdrError::ErrorType
            printString(TdrWriteBuf& buf, int indent, char sep,
                        const char* variable, const char* str);

        static TdrError::ErrorType
            printString(TdrWriteBuf& buf, int indent, char sep,
                        const char* variable, unsigned int arrIdx, const char* str);

        static TdrError::ErrorType
            printWString(TdrWriteBuf& buf, int indent, char sep,
                        const char* variable, const tdr_wchar_t* str);

        static TdrError::ErrorType
            printWString(TdrWriteBuf& buf, int indent, char sep,
                        const char* variable, unsigned int arrIdx, const tdr_wchar_t* str);

        static TdrError::ErrorType
            printTdrIP(TdrWriteBuf& buf, int indent, char sep,
                    const char* variable, tdr_ip_t tdrIp);

        static TdrError::ErrorType
            printTdrIP(TdrWriteBuf& buf, int indent, char sep,
                    const char* variable, unsigned int arrIdx, tdr_ip_t tdrIp);

        static TdrError::ErrorType
            printTdrTime(TdrWriteBuf& buf, int indent, char sep,
                        const char* variable, tdr_time_t tdrTime);

        static TdrError::ErrorType
            printTdrTime(TdrWriteBuf& buf, int indent, char sep,
                        const char* variable, unsigned int arrIdx, tdr_time_t tdrTime);

        static TdrError::ErrorType
            printTdrDate(TdrWriteBuf& buf, int indent, char sep,
                        const char* variable, tdr_date_t tdrDate);

        static TdrError::ErrorType
            printTdrDate(TdrWriteBuf& buf, int indent, char sep,
                        const char* variable, unsigned int arrIdx, tdr_date_t tdrDate);

        static TdrError::ErrorType
            printTdrDateTime(TdrWriteBuf& buf, int indent, char sep,
                            const char* variable, tdr_datetime_t tdrDateTime);

        static TdrError::ErrorType
            printTdrDateTime(TdrWriteBuf& buf, int indent, char sep,
                            const char* variable, unsigned int arrIdx, tdr_datetime_t tdrDateTime);
};

}
#endif
